### ISSUE TITLE
daemon does not stop

### ISSUE THREAD

**Issue by ihard** [go-graphite/go-carbon#135]
Ubuntu 16.04
go-carbon 0.9

if in config
[dump]
enabled = false

daemon not stop, it does not react to the signal USR2

**Comment by lomik** [comment]
Why do you expect that the demon will stop at usr2? If dump disabled USR2 don't do anything.

**Comment by ihard** [comment]
In script 
/etc/init.d/go-carbon
...
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --signal USR2 --pidfile $PIDFILE --exec $DAEMON
	RETVAL="$?"
	return "$RETVAL"
}
...
init script does not know what is specified in go-carbon.conf and send signal USR2 always

**Comment by lomik** [comment]
Fixed in 0.9.1

**Comment by AlexAkulov** [comment]
Hello! Problem is still exists.
go-carbon log
```
[2017-05-05T10:39:53.133+0300] INFO [dump] grace stop with dump inited {}
[2017-05-05T10:39:53.135+0300] INFO [dump] start cache dump {"filename": "/data/graphite/dump/cache.27857.1493969993135084399.bin"}
[2017-05-05T10:39:53.135+0300] INFO [dump] start wal write {"filename": "/data/graphite/dump/input.27857.1493969993135084399"}
[2017-05-05T10:39:55.229+0300] INFO [dump] cache dump finished {"records": 10313179, "runtime": 2.092683896}
[2017-05-05T10:39:55.229+0300] INFO [dump] stop listeners {}
```
more here https://pastebin.com/tGdirFEz

```
[root@vm-graphite-s1 /opt/go-carbon]# lsof -p `pgrep go-carbon`
COMMAND     PID     USER   FD      TYPE             DEVICE SIZE/OFF       NODE NAME
go-carbon 40778 graphite  cwd       DIR              253,0     4096        192 /
go-carbon 40778 graphite  rtd       DIR              253,0     4096        192 /
go-carbon 40778 graphite  txt       REG              253,0 11885872  545652863 /opt/go-carbon/go-carbon
go-carbon 40778 graphite  mem       REG              253,0    61928 1074395479 /usr/lib64/libnss_files-2.17.so
go-carbon 40778 graphite  mem       REG              253,0  2112384 1074395461 /usr/lib64/libc-2.17.so
go-carbon 40778 graphite  mem       REG              253,0   142304 1074395487 /usr/lib64/libpthread-2.17.so
go-carbon 40778 graphite  mem       REG              253,0   164440 1074352637 /usr/lib64/ld-2.17.so
go-carbon 40778 graphite    0r      CHR                1,3      0t0       1028 /dev/null
go-carbon 40778 graphite    1u     unix 0xffff880081236c00      0t0   85843886 socket
go-carbon 40778 graphite    2u     unix 0xffff880081236c00      0t0   85843886 socket
go-carbon 40778 graphite    3w      REG              253,0  4103317     929507 /var/log/go-carbon/go-carbon.log
go-carbon 40778 graphite    4u     IPv6           85765813      0t0        TCP *:7555 (LISTEN)
go-carbon 40778 graphite    5u  a_inode                0,9        0       6259 [eventpoll]
go-carbon 40778 graphite    7u     IPv6           85843889      0t0        TCP *:irdmi (LISTEN)
go-carbon 40778 graphite   12u      REG              253,0  4194304 3258354766 /data/graphite/dump/input.40778.1493973661567923491
```
pprof on 7555 port
carbonserver on 8000 port (irdmi?)

**Comment by lomik** [comment]
New fixes added in master:
* stop carbonserver asynchronously
* force stop daemon in 5 seconds after dump finished (just in case)
